### ISSUE TITLE
[Feature Request] Next/Previous Track Action

### ISSUE THREAD

**Issue by tobru** [confirm/mopidy-pummeluff#13]
When working with playlists it would also be great to have a tag to skip forward to the next track or back to the previous one in the playlist. This "Class" is currently not available and it would be fantastic to have it available.

**Comment by domibarton** [comment]
Should be doable… let me peek at the official Mopidy API.

**Comment by domibarton** [comment]
YAY… Should be really simple, as it's the same playback controller class as the `play` / `resume` one:

https://docs.mopidy.com/en/latest/api/core/#mopidy.core.PlaybackController.next

**Comment by tobru** [comment]
I'll give it a try with a PR in the next days :+1:

**Comment by domibarton** [comment]
No worries, I already have it :)

**Comment by domibarton** [comment]
I'll probably refactor the code a bit to keep compliant with DRY

**Comment by domibarton** [comment]
I created a new [PR](#14) for my new [`add-next-previous-actions` branch](https://github.com/confirm/mopidy-pummeluff/tree/add-next-previous-actions). However, I couldn't test the changes yet, because I currently don't have the box at home. I'll give it a try in the next days.

What I can say so far:

- I merged the `action` functions and `Tag` classes into `Action` classes
- I created new `PreviousTrack` and `NextTrack` actions
- I assigned those actions to new GPIO pins
- I move the pins for the buttons (see [new README](https://github.com/confirm/mopidy-pummeluff/blob/add-next-previous-actions/README.rst))

Again: I only changed the code on the fly without testing. I'd be surprised if that change already works ^^

**Comment by domibarton** [comment]
@tobru I created a [new release](https://github.com/confirm/mopidy-pummeluff/releases/tag/v2.2.0).

You can use the tag `v2.2.0`, the `master` branch or the new [PyPi package](https://pypi.org/project/Mopidy-Pummeluff/2.2.0/).

Can you test if everything works as expected and let me know? :)

**Comment by tobru** [comment]
@domibarton I can confirm that it just works :tm: :tada: I'm even impressed that you could read my mind about the new unregister tag possibility which was a thing I was thinking about.

Thank you very much, I owe you a :beer: once it's possible again!

**Comment by domibarton** [comment]
lolz :D after the corona thingy, we'll have some 🍻 ;)

Yeah the "unregister" feature was in my mind for some time. But I'm a lazy person, so it took some time. Glad it worked :)
